name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.2
  google_sign_in: ^6.3.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.1
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
    - assets/jihc-logo-png-v3 2.png
    - assets/facebook.png
    - assets/facebook.png
    - assets/DSC03364.JPG
    - assets/DSC00297.JPG
    - assets/photo_5350782979229739772_y.jpg
    - assets/DSC03741.JPG
    - assets/Screenshot 2025-05-21 at 15.55.36.png

flutter_native_splash:
  color: "#E57DC6"
  image: assets/logo.png
  android: true
  ios: true
  fullscreen: true
