// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX4mrwZ9BMc41Rbl4jOQDSStSMaP81-H4',
    appId: '1:930451288873:web:6202e73ed932b94ee5bd38',
    messagingSenderId: '930451288873',
    projectId: 'eventhub-25bef',
    authDomain: 'eventhub-25bef.firebaseapp.com',
    storageBucket: 'eventhub-25bef.firebasestorage.app',
    measurementId: 'G-4S3FXX3FCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQYDNioMXDzJHvJ0-baEpJAxCXkzmozNQ',
    appId: '1:930451288873:android:9cd3f791f3e3eabce5bd38',
    messagingSenderId: '930451288873',
    projectId: 'eventhub-25bef',
    storageBucket: 'eventhub-25bef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuqADc7Q7IJFaExSHg-OeLYRaG3j5Z2eA',
    appId: '1:930451288873:ios:247b348c805f2e3ee5bd38',
    messagingSenderId: '930451288873',
    projectId: 'eventhub-25bef',
    storageBucket: 'eventhub-25bef.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuqADc7Q7IJFaExSHg-OeLYRaG3j5Z2eA',
    appId: '1:930451288873:ios:247b348c805f2e3ee5bd38',
    messagingSenderId: '930451288873',
    projectId: 'eventhub-25bef',
    storageBucket: 'eventhub-25bef.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX4mrwZ9BMc41Rbl4jOQDSStSMaP81-H4',
    appId: '1:930451288873:web:a25d3c078bd45522e5bd38',
    messagingSenderId: '930451288873',
    projectId: 'eventhub-25bef',
    authDomain: 'eventhub-25bef.firebaseapp.com',
    storageBucket: 'eventhub-25bef.firebasestorage.app',
    measurementId: 'G-ZN809GEB70',
  );
}
